# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


                         

parameters:
  - name: mach
    type: string
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - windows-latest
      - mac 
  
pool:
  vmImage: ubuntu-latest
variables:
- name: myvar
  value: ${{parameters.mach}}
stages: 
 - stage: stage2
   jobs:
     - job: "job2"
       condition: eq(variables.myvar,'ubuntu-latest')
       steps: 
        - script: "echo job2 running"
 
       
   
       
   

          
   

