# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


                         
trigger:
  branches:
    include:
     - "*"
  tags:
   include:
     - "*"
pr:
 branches:
   include:
     - "*"
schedules:
  - cron: "* 18 * * 1-5"
    branches:
     include:
       - master
pool:
  vmImage: ubuntu-latest
stages:
 - stage: stage1
   pool:
    vmImage: windows-latest
   jobs:
    - job: job1
      steps:
       - script: |
           echo "this is job1"
          # sh exit1
 - stage: stage2
   jobs:
     - job: job2
       condition: succeeded('A')
       steps: 
        - script: "echo job2 running"
       
   

          
   

