# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: stage1
    jobs:
     - job: job1
       steps:
         - script: exit 1
    
  - stage: stage2
    condition: always()
    jobs:
     - job:
       steps:
         - script:  echo "job2"
    
  
     
 
       
   
       
   

          
   

