# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: stage1
    jobs:
     - job:
       steps:
         - script:  echo "job1"
    
  - stage: stage2
    dependsOn: stage1
    jobs:
     - job:
       steps:
         - script:  echo "job2"
    
  - stage: stage3
    dependsOn: stage1
    jobs:
     - job: job3

  - stage: stage4
    dependsOn: 
     - stage2
     - stage3
    jobs:
     - job: job4
     
 
       
   
       
   

          
   

