# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- main
                         
parameters:
  - name: boolen
    type: boolean
    default: true
pool:
  vmImage: ubuntu-latest
stages:
 - stage: stage1
   pool:
    vmImage: windows-latest
   jobs:
    - job: "job1"
      steps:
       - script: |
           echo "this is job1"
        
 - stage: stage2
   dependsOn: []
   jobs:
     - job: "job2"
       
       steps: 
        - script: "echo job2 running"
 
       
   
       
   

          
   

