# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: stage1
    jobs:
     - job: job1
       steps:
        - task: Maven@4
         


    
  - stage: stage2
    condition: failed('job1')
    jobs:
     - job: job2
       steps:
         - script:  echo "job2 running"
    
  
     
 
       
   
       
   

          
   

