# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main
pool:
  vmImage: ubuntu-latest
stages:
 - stage: stage1
   jobs:
     - job: job1
 - stage: stage2
   jobs:
     - job: job2
       steps:
       - script: |
          echo "Hello everyone"
 - stage: stage3
   displayName: "stag3 depends on one"
   dependsOn: stage1
   jobs:
     - job: job3
       steps:
         - script: echo "stage 3 executed successfully"
         - task: CmdLine@2
           inputs:
              script: |
                echo Write your commands here
                echo "stage 3 with task"
             
            
        
          
   

